export { Repository } from "./Repository.js";
export { PaginationEngine } from "./pagination/PaginationEngine.js";
export { fieldFilterPlugin } from "./plugins/field-filter.plugin.js";
export { timestampPlugin } from "./plugins/timestamp.plugin.js";
export { auditLogPlugin } from "./plugins/audit-log.plugin.js";
export { softDeletePlugin } from "./plugins/soft-delete.plugin.js";
export { methodRegistryPlugin } from "./plugins/method-registry.plugin.js";
export { mongoOperationsPlugin } from "./plugins/mongo-operations.plugin.js";
export { batchOperationsPlugin } from "./plugins/batch-operations.plugin.js";
export { aggregateHelpersPlugin } from "./plugins/aggregate-helpers.plugin.js";
export { subdocumentPlugin } from "./plugins/subdocument.plugin.js";
export * as actions from "./actions/index.js";
export function createRepository(Model: any, plugins?: any[]): Repository;
export default Repository;
export type PaginationConfig = import("./pagination/PaginationEngine.js").PaginationConfig;
export type OffsetPaginationOptions = import("./pagination/PaginationEngine.js").OffsetPaginationOptions;
export type KeysetPaginationOptions = import("./pagination/PaginationEngine.js").KeysetPaginationOptions;
export type AggregatePaginationOptions = import("./pagination/PaginationEngine.js").AggregatePaginationOptions;
export type OffsetPaginationResult = import("./pagination/PaginationEngine.js").OffsetPaginationResult;
export type KeysetPaginationResult = import("./pagination/PaginationEngine.js").KeysetPaginationResult;
export type AggregatePaginationResult = import("./pagination/PaginationEngine.js").AggregatePaginationResult;
import { Repository } from './Repository.js';
export { validationChainPlugin, blockIf, requireField, autoInject, immutableField, uniqueField } from "./plugins/validation-chain.plugin.js";
export { getFieldsForUser, getMongooseProjection, filterResponseData, createFieldPreset } from "./utils/field-selection.js";
//# sourceMappingURL=index.d.ts.map